# Generated by Django 6.1.1 on 2026-09-20 16:23

import django.core.validators
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='primary_image',
            field=models.ImageField(upload_to='vehicles/primary/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), vehicles.models.validate_vehicle_image]),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/supporting/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), vehicles.models.validate_vehicle_image]),
        ),
    ]
