# Generated by Django 6.1.1 on 2026-09-21 21:33

import bookings.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_alter_vehicle_primary_image_alter_vehicleimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=bookings.models.generate_booking_reference, editable=False, max_length=11, unique=True)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('rate_per_day', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rental_days', models.PositiveIntegerField(editable=False)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx'), models.Index(fields=['vehicle', 'status'], name='bookings_bo_vehicle_fba60e_idx'), models.Index(fields=['pickup_date', 'return_date'], name='bookings_bo_pickup__8f81fe_idx')],
            },
        ),
    ]
